-- Schema definitions for tiktok_ads
-- Auto-extracted from sources/tiktok_ads/postgres.sh

-- Table: tiktok_ad_report_hourly
CREATE TABLE IF NOT EXISTS tiktok_ad_report_hourly (
    ad_id INTEGER,
    stat_time_hour TIMESTAMP WITHOUT TIME ZONE,
    cost_per_conversion DOUBLE PRECISION,
    cpc DOUBLE PRECISION,
    video_play_actions INTEGER,
    conversion_rate INTEGER,
    video_views_p_75 INTEGER,
    result INTEGER,
    video_views_p_50 INTEGER,
    impressions INTEGER,
    comments INTEGER,
    real_time_cost_per_result DOUBLE PRECISION,
    conversion INTEGER,
    real_time_result INTEGER,
    video_views_p_100 INTEGER,
    shares INTEGER,
    real_time_conversion_rate INTEGER,
    cost_per_secondary_goal_result TEXT,
    secondary_goal_result_rate TEXT,
    clicks INTEGER,
    cost_per_1000_reached INTEGER,
    video_views_p_25 INTEGER,
    reach INTEGER,
    real_time_cost_per_conversion DOUBLE PRECISION,
    profile_visits_rate INTEGER,
    average_video_play DOUBLE PRECISION,
    profile_visits INTEGER,
    cpm DOUBLE PRECISION,
    ctr DOUBLE PRECISION,
    video_watched_2_s INTEGER,
    follows INTEGER,
    result_rate INTEGER,
    video_watched_6_s INTEGER,
    secondary_goal_result TEXT,
    cost_per_result DOUBLE PRECISION,
    average_video_play_per_user INTEGER,
    real_time_result_rate INTEGER,
    spend DOUBLE PRECISION,
    likes INTEGER,
    real_time_conversion INTEGER,
    total_purchase_value DOUBLE PRECISION,
    total_sales_lead_value DOUBLE PRECISION,
    _fivetran_synced TEXT
);

-- Table: tiktok_adgroup_report_hourly
CREATE TABLE IF NOT EXISTS tiktok_adgroup_report_hourly (
    adgroup_id INTEGER,
    stat_time_hour TIMESTAMP WITHOUT TIME ZONE,
    cost_per_conversion DOUBLE PRECISION,
    cpc DOUBLE PRECISION,
    video_play_actions INTEGER,
    conversion_rate INTEGER,
    video_views_p_75 INTEGER,
    result INTEGER,
    video_views_p_50 INTEGER,
    impressions INTEGER,
    comments INTEGER,
    real_time_cost_per_result DOUBLE PRECISION,
    conversion INTEGER,
    real_time_result INTEGER,
    video_views_p_100 INTEGER,
    shares INTEGER,
    real_time_conversion_rate DOUBLE PRECISION,
    cost_per_secondary_goal_result TEXT,
    secondary_goal_result_rate TEXT,
    clicks INTEGER,
    cost_per_1000_reached DOUBLE PRECISION,
    video_views_p_25 INTEGER,
    reach INTEGER,
    real_time_cost_per_conversion DOUBLE PRECISION,
    profile_visits_rate INTEGER,
    average_video_play DOUBLE PRECISION,
    profile_visits INTEGER,
    cpm DOUBLE PRECISION,
    ctr DOUBLE PRECISION,
    video_watched_2_s INTEGER,
    follows INTEGER,
    result_rate DOUBLE PRECISION,
    video_watched_6_s INTEGER,
    secondary_goal_result TEXT,
    cost_per_result DOUBLE PRECISION,
    average_video_play_per_user DOUBLE PRECISION,
    real_time_result_rate DOUBLE PRECISION,
    spend DOUBLE PRECISION,
    likes INTEGER,
    real_time_conversion INTEGER,
    total_purchase_value DOUBLE PRECISION,
    total_sales_lead_value DOUBLE PRECISION,
    _fivetran_synced TEXT
);

