Airbyte:
  config:
    files_definition_id: 778daa7c-feaf-4db6-96f3-70fd645acc77
    namespace_definition: destination
    server_url: http://airbyte-abctl-control-plane:80/api/public/v1/
    redshift_definition_id: f7a7d195-377f-cf5b-70a5-be6b819019dc
custom_api:
  config:
    configuration: {}
    sync_mode: full_refresh_append
    tables:
    - matchs
flat_files:
- format: csv
  path: https://drive.google.com/uc?export=download&id=1KFZsbn9RfhpNEQSvoBV7wUie5x5MP4XP
  sync_mode: full_refresh_append
  table: divisions
redshift:
  config:
    host: <redshift_hostname>
    port: <redshift_port>
    database: <redshift_db>
    username: <redshift_username>
    password: <redshift_pwd>
    schema: european_football_1
    s3_bucket_name: <redshift_s3_bucket>
    s3_bucket_region: <redshift_s3_region>
    access_key_id: <redshift_s3_access_key>
    secret_access_key: <redshift_s3_secret_key>
