Airbyte:
  config:
    namespace_definition: destination
    postgres_definition_id: decd338e-5647-4c0b-adf4-da0e75f5a750
    server_url: http://airbyte-abctl-control-plane:80/api/public/v1/
    redshift_definition_id: f7a7d195-377f-cf5b-70a5-be6b819019dc
custom_api:
  config:
    configuration: {}
    sync_mode: full_refresh_append
    tables:
    - coins
postgres:
  config:
    database: coinmarketcap
    host: elt-postgres
    password: testelt
    port: 5432
    schema: public
    sync_mode: full_refresh_append
    tables:
    - historical
    user: postgres
redshift:
  config:
    host: <redshift_hostname>
    port: <redshift_port>
    database: <redshift_db>
    username: <redshift_username>
    password: <redshift_pwd>
    schema: coinmarketcap
    s3_bucket_name: <redshift_s3_bucket>
    s3_bucket_region: <redshift_s3_region>
    access_key_id: <redshift_s3_access_key>
    secret_access_key: <redshift_s3_secret_key>
