Airbyte:
  config:
    files_definition_id: 778daa7c-feaf-4db6-96f3-70fd645acc77
    mongodb_definition_id: b2e713cd-cc36-4c0a-b5bd-b47cb8a0561e
    namespace_definition: destination
    postgres_definition_id: decd338e-5647-4c0b-adf4-da0e75f5a750
    server_url: http://airbyte-abctl-control-plane:80/api/public/v1/
    databricks_definition_id: 072d5540-f236-4294-ba7c-ade8fd918496
custom_api:
  config:
    configuration: {}
    sync_mode: full_refresh_append
    tables:
    - bond
flat_files:
- format: csv
  path: https://drive.google.com/uc?export=download&id=1xbdYAJ2BFSdjfRKwAEjqguRMK9EcNSH4
  sync_mode: full_refresh_append
  table: molecule
mongodb:
  config:
    connection_string: mongodb://elt-mongodb:27017/?directConnection=true
    database: toxicology
    sync_mode: full_refresh_append
    tables:
    - atom
postgres:
  config:
    database: toxicology
    host: elt-postgres
    password: testelt
    port: 5432
    schema: public
    sync_mode: full_refresh_append
    tables:
    - connected
    user: postgres
databricks:
  config:
    database: <db_database>
    hostname: <db_hostname>
    client_id: <db_client_id>
    secret: <db_secret>
    schema: toxicology
    http_path: <db_path>
